lec10-1/config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  resources :items
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'main/login'
  post 'main/create'
  post 'main/user_Item_delete', to: 'main#user_Item_delete'
  get 'main/destroy'
  get 'main/user_Item', to: 'main#user_Items'

  get 'shop/:id', to: 'main#show_shop'
  post 'main/buy_item', to: 'main#buy_item'

  get 'main/inventories', to: 'main#show_inventory'

  # Defines the root path route ("/")
  # root "articles#index"
end

lec10-1/app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

lec10-1/app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Inventory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:user_id, :item_id, :price, :timestamp)
    end
end

lec10-1/app/helpers/inventories_helper.rb
module InventoriesHelper
end

lec10-1/app/views/inventories/_form.html.haml
= form_for @inventory do |f|
  - if @inventory.errors.any?
    #error_explanation
      %h2= "#{pluralize(@inventory.errors.count, "error")} prohibited this inventory from being saved:"
      %ul
        - @inventory.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :item
    = f.text_field :item
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :timestamp
    = f.datetime_field :timestamp
  .actions
    = f.submit 'Save'

lec10-1/app/views/inventories/edit.html.haml
%h1 Editing inventory

= render 'form'

= link_to 'Show', @inventory
\|
= link_to 'Back', inventories_path

lec10-1/app/views/inventories/index.html.haml
%h1 Listing inventories

%table
  %thead
    %tr
      %th User
      %th Item
      %th Price
      %th Timestamp
      %th
      %th
      %th

  %tbody
    - @inventories.each do |inventory|
      %tr
        %td= inventory.user
        %td= inventory.item
        %td= inventory.price
        %td= inventory.timestamp
        %td= link_to 'Show', inventory
        %td= link_to 'Edit', edit_inventory_path(inventory)
        %td= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Inventory', new_inventory_path

lec10-1/app/views/inventories/new.html.haml
%h1 New inventory

= render 'form'

= link_to 'Back', inventories_path

lec10-1/app/views/inventories/show.html.haml
%p#notice= notice

%p
  %b User:
  = @inventory.user
%p
  %b Item:
  = @inventory.item
%p
  %b Price:
  = @inventory.price
%p
  %b Timestamp:
  = @inventory.timestamp

= link_to 'Edit', edit_inventory_path(@inventory)
\|
= link_to 'Back', inventories_path